name: 'Set up postgres'
description: 'Set up postgres database for dbt tests'
runs:
  using: "composite"
  steps:
    - name: Set up postgres (ubuntu)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo systemctl start postgresql.service
        pg_isready
        sudo -u postgres bash ${{ github.action_path }}/setup.sh

    - name: Set up postgres (macos)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew services start postgresql
        echo "Check PostgreSQL service is running"
        i=10
        COMMAND='pg_isready'
        while [ $i -gt 0 ]; do
            echo "Check PostgreSQL service status"
            eval $COMMAND && break
            ((i--))
            if [ $i == 0 ]; then
                echo "PostgreSQL service not ready, all attempts exhausted"
                exit 1
            fi
            echo "PostgreSQL service not ready, wait 10 more sec, attempts left: $i"
            sleep 10
        done
        createuser -s postgres
        bash ${{ github.action_path }}/setup.sh

    - name: Set up postgres (windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $pgService = Get-Service -Name postgresql*
        Set-Service -InputObject $pgService -Status running -StartupType automatic
        Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru
        $env:Path += ";$env:PGBIN"
        bash ${{ github.action_path }}/setup.sh
