# **what?**
# This workflow contains static code checks. This workflow
# should require no secrets since it will be triggered for all pushes, PRs, and
# forked PRs. Secrets are not passed to workflows from forked PRs.

# **why?**
# To ensure all code being merged into the project passes a
# minimum threshold of quality.

# **when?**
# This workflow will run on every push to a protected
# branch, for all pull requests, and when manually triggered.

name: Lint

on:
  push:
    branches:
      - "main"
      - "develop"
      - "*.latest"
      - "releases/*"
  pull_request:
  workflow_dispatch:

permissions: read-all

concurrency:
  group: lint-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toxenv: [flake8, mypy]

    env:
      TOXENV: ${{ matrix.toxenv }}
      PYTEST_ADDOPTS: "-v --color=yes"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Upgrade python dependencies
        run: |
          python -m pip install --upgrade pip
          pip --version

      - name: Install tox
        run: |
          pip install tox
          tox --version

      - name: Run tox
        run: tox
